# Generated by Django 2.0.5 on 2018-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncalarm',
            name='alarmName',
            field=models.CharField(default='OverHot', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cnc',
            name='reservedField_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cnc',
            name='reservedField_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cnc',
            name='reservedField_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cnc',
            name='reservedField_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cnc',
            name='reservedField_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cncalarm',
            name='alarmAppearance',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='cncalarm',
            name='alarmReason',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='cncalarm',
            name='alarmSolution',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
